Platform:
  billing:
    trail-period-days: 7

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/streaming_api_db
    username: devuser
    password: devsecret
  jpa:
    hibernate:
      ddl-auto: none